swagger: '2.0'
info:
  version: 0.1.2
  title: changelog parser
  description: Microservice for parsing changelog documents into json objects
  contact:
    email: "dooley@tacc.utexas.edu"
  termsOfService: "http://agaveapi.co/terms"
  license:
    name: "BSD 2-Clause"
    url: "https://opensource.org/licenses/BSD-2-Clause"
host: "agaveapi.co"
basePath: "/"
schemes:
- "https"
- "http"
consumes:
- "application/json"
produces:
- "application/json"


tags:
  -
    name: "parser"
    description: ""
paths:
  "/changelog-parser":
    get:
      tags:
        - "parser"
      responses:
        200:
          description: "changelog json"
        500:
          description: "internal error"
      description: ""
      summary: "Get list of all actors"
      operationId: "getActors"
      produces:
        - "application/json"
      parameters:
        -
          in: "query"
          description: "URL of the changelog to parse"
          name: "source"
          required: true
          type: "string"
        -
          in: "query"
          description: "Should the cached value be invalidated"
          name: "force"
          required: false
          type: "boolean"
        -
          in: "query"
          description: "Return only the latest entry in the changelog"
          name: "latest"
          required: false
          type: "boolean"
